# Generated by Django 5.1.3 on 2025-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
