# Generated by Django 5.1.3 on 2025-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
