# Generated by Django 5.1.3 on 2025-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=12, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
