# Generated by Django 5.1.3 on 2025-07-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccess',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='download',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='email',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='password',
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='username',
        ),
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='credential',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='product.credential'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
