# Generated by Django 5.1.3 on 2025-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productaccess_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
