# Generated by Django 5.1.3 on 2025-04-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_payment_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccess',
            name='cookies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=100),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('download', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributeOption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='product.attributeoption')),
                ('prodduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='product.product')),
            ],
        ),
    ]
