# Generated by Django 5.1.3 on 2025-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productaccess_cookies_alter_order_status_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credential',
            name='access_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credential',
            name='access_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='access_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='access_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
