# Generated by Django 5.1.3 on 2025-04-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_credential_access_count_credential_access_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaccess',
            old_name='access_time',
            new_name='expired_date',
        ),
    ]
