# Generated by Django 5.1.3 on 2025-05-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_access_time_productaccess_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccess',
            name='attributeOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='product.attributeoption'),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='prodduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='product.orderproduct'),
        ),
    ]
