# Generated by Django 5.1.3 on 2025-05-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='download',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='email',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='note',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='password',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='username',
        ),
    ]
