# Generated by Django 5.1.3 on 2025-05-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_credential_download_remove_credential_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='attributeOption',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='prodduct',
        ),
    ]
