# Generated by Django 5.1.3 on 2025-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_credential_attributeoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='access_time',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='credential',
            name='download',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
