# Generated by Django 5.1.3 on 2025-05-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_credential_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
