# Generated by Django 5.1.3 on 2025-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_credential_access_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='access_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
